# Generated by Django 5.2.7 on 2025-12-07 13:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models.brokerProfile
import users.utils.dummy_relations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('BROKER', 'Broker'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dummy1', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy2', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy3', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy4', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy5', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('pvt_ltd', 'Private Limited Company'), ('llp', 'LLP'), ('others', 'Others')], db_index=True, default='individual', max_length=30)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=40)),
                ('official_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('arn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('arn_document', models.FileField(blank=True, null=True, upload_to='onboarding/arn/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('arn_expiry_date', models.DateField(blank=True, null=True)),
                ('aprn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('aprn_document', models.FileField(blank=True, null=True, upload_to='onboarding/aprn/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('aprn_expiry_date', models.DateField(blank=True, null=True)),
                ('products_allowed', models.JSONField(blank=True, default=list)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='onboarding/pan/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='onboarding/cheques/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('pincode', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(default='India', max_length=80)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='onboarding/address_proofs/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='onboarding/agreements/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(600, ['pdf'])])),
                ('moa_aoa', models.FileField(blank=True, null=True, upload_to='onboarding/entity_docs/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('board_resolution', models.FileField(blank=True, null=True, upload_to='onboarding/entity_docs/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('partnership_deed', models.FileField(blank=True, null=True, upload_to='onboarding/entity_docs/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_document', models.FileField(blank=True, null=True, upload_to='onboarding/gst/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('auth_signatory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_signatory_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auth_signatory_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('auth_signatory_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('auth_signatory_kyc', models.FileField(blank=True, null=True, upload_to='onboarding/signatory_kyc/', validators=[users.models.brokerProfile.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_brokers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_profiles', to='users.employeeprofile')),
            ],
            options={
                'verbose_name': 'Broker Onboarding',
                'verbose_name_plural': 'Broker Onboardings',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN (e.g. ABCDE1234F). Use uppercase letters.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('pan_copy', models.FileField(blank=True, null=True, upload_to='uploads/pan/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='uploads/address/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(default=users.utils.dummy_relations.get_default_broker, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.brokerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(default=users.utils.dummy_relations.get_default_employee, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pan'], name='users_custo_pan_27a102_idx'), models.Index(fields=['mobile'], name='users_custo_mobile_61a1bf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['account_type'], name='users_broke_account_16dbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['pan_number'], name='users_broke_pan_num_6193ae_idx'),
        ),
    ]
