# Generated by Django 5.2.7 on 2025-12-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerprofile',
            options={'verbose_name': 'Broker profile', 'verbose_name_plural': 'Broker profiles'},
        ),
    ]
