# Generated by Django 5.2.7 on 2025-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_brokerprofile_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='users_custo_mobile_61a1bf_idx',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='mobile',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='mobile',
            new_name='contact_phone',
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['contact_phone'], name='users_custo_contact_2b30ce_idx'),
        ),
    ]
