# Generated by Django 5.2.7 on 2025-12-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customerprofile_users_custo_mobile_61a1bf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='contact_phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN (e.g. ABCDE1234F). Use uppercase letters.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contact_phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
