# Generated by Django 5.2.7 on 2025-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_brokerprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
