# Generated by Django 5.2.7 on 2025-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_brokerprofile_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
