# Generated by Django 5.2.8 on 2025-12-23 10:16

import django.db.models.deletion
import users.utils.dummy_relations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_brokerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='broker',
            field=models.ForeignKey(blank=True, default=users.utils.dummy_relations.get_default_broker, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.brokerprofile'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='employee',
            field=models.ForeignKey(blank=True, default=users.utils.dummy_relations.get_default_employee, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.employeeprofile'),
        ),
    ]
