# Generated by Django 5.2.8 on 2025-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customerprofile_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
