# Generated by Django 5.2.7 on 2025-12-24 12:24

import django.db.models.deletion
import users.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employeeprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_signatory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_signatory_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auth_signatory_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('auth_signatory_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('auth_signatory_kyc', models.FileField(blank=True, null=True, upload_to='onboarding/signatory_kyc/', validators=[users.validators.validators.MigrationSafeFileValidators(500, ['pdf', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Authorized Signatory',
                'verbose_name_plural': 'Authorized Signatories',
            },
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='auth_signatory_email',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='auth_signatory_kyc',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='auth_signatory_name',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='auth_signatory_pan',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='auth_signatory_phone',
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='broker_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['broker_code'], name='users_broke_broker__57e589_idx'),
        ),
        migrations.AddField(
            model_name='authorizedsignatory',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_signatories', to='users.brokerprofile'),
        ),
    ]
