# Generated by Django 5.2.7 on 2025-12-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.brokerprofile'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.employeeprofile'),
        ),
    ]
