# Generated by Django 5.2.7 on 2025-12-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customerprofile_broker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerprofile',
            options={'ordering': ['-id'], 'verbose_name': 'Broker profile', 'verbose_name_plural': 'Broker profiles'},
        ),
    ]
