# Generated by Django 5.2.7 on 2025-12-25 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_brokerprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN (e.g. ABCDE1234F). Use uppercase letters.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
