# Generated by Django 5.2.7 on 2025-12-25 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customerprofile_pan'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='users_custo_pan_27a102_idx',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN (e.g. ABCDE1234F). Use uppercase letters.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['email'], name='users_custo_email_26a95f_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('pan__isnull', False)), fields=('pan',), name='unique_pan_when_present'),
        ),
    ]
