# Generated by Django 5.2.7 on 2025-11-21 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='The generated OTP code', max_length=10)),
                ('email', models.EmailField(blank=True, help_text='Email address for sending OTP', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number for sending OTP', max_length=15, null=True)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login Authentication'), ('SIGNUP', 'New Account Creation'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('TRANSACTION_VERIFICATION', 'Transaction Verification'), ('PROFILE_UPDATE', 'Profile Update'), ('OTHER', 'Other Purpose')], default='OTHER', help_text='Purpose for which this OTP was generated', max_length=30)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('DELIVERED', 'Delivered'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('INVALIDATED', 'Invalidated')], default='CREATED', help_text='Current status of this OTP', max_length=20)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Both Email and SMS')], default='EMAIL', help_text='Method used to deliver the OTP', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the OTP was generated')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the OTP was sent', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the OTP was successfully verified', null=True)),
                ('expires_at', models.DateTimeField(help_text='When the OTP will expire')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the requester', null=True)),
                ('additional_info', models.JSONField(blank=True, help_text='Additional information as needed', null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts made')),
            ],
            options={
                'verbose_name': 'OTP Transaction',
                'verbose_name_plural': 'OTP Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
