# Generated by Django 5.2.7 on 2025-12-07 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otptransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this OTP (can be null for signup)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otptransaction',
            index=models.Index(fields=['-created_at'], name='otps_otptra_created_49a071_idx'),
        ),
        migrations.AddIndex(
            model_name='otptransaction',
            index=models.Index(fields=['email', '-created_at'], name='otps_otptra_email_ce02aa_idx'),
        ),
        migrations.AddIndex(
            model_name='otptransaction',
            index=models.Index(fields=['user', '-created_at'], name='otps_otptra_user_id_129b71_idx'),
        ),
        migrations.AddIndex(
            model_name='otptransaction',
            index=models.Index(fields=['otp_code'], name='otps_otptra_otp_cod_68e399_idx'),
        ),
        migrations.AddIndex(
            model_name='otptransaction',
            index=models.Index(fields=['status'], name='otps_otptra_status_60d9ca_idx'),
        ),
    ]
