# Generated by Django 5.2.7 on 2026-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('query', models.TextField(max_length=2000)),
                ('use_whatsapp', models.BooleanField(default=False)),
                ('agree_tos', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed')], default='NEW', help_text='Internal handling status', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['email'], name='homepage_co_email_4f59d4_idx'), models.Index(fields=['mobile'], name='homepage_co_mobile_fd357f_idx'), models.Index(fields=['status', 'submitted_at'], name='homepage_co_status_88d587_idx')],
            },
        ),
    ]
